services:
  node:
    build:
      dockerfile: dev.Dockerfile
      context: ./backend
    volumes:
    - type: bind
      source: ./backend
      target: /code/backend

    # Create a data volume to prevent node_modules from being overwritten
    - backend_node_modules:/code/backend/node_modules

  nginx:
    build:
      dockerfile: dev.Dockerfile
      context: ./nginx
    volumes:
      - type: bind
        source: ./build/development
        target: /code/build/development
    depends_on:
      - webpack
    ports:
      - 8000:8000

  webpack:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /code/frontend

      # Create a data volume to prevent node_modules from being overwritten
      - frontend_node_modules:/code/frontend/node_modules

      - type: bind
        source: ./build/development
        target: /code/build/development

volumes:
  frontend_node_modules:
  backend_node_modules: