version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  django:
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SECRET_KEY
      - ENVIRONMENT
      - POSTGRES_HOST
    depends_on:
      - postgres

  nginx:
    depends_on:
      - django
