version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  node:
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - NODE_ENV
    depends_on:
      - postgres

  nginx:
    depends_on:
      - node
