services:
  postgres:
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data

  node:
    image: junnys/emulator-hub_node:${APPLICATION_VERSION}

  nginx:
    image: junnys/emulator-hub_nginx:${APPLICATION_VERSION}
    ports:
      - ${PORT}:8080

volumes:
  dbdata:
