name: Tests

on: [push, workflow_dispatch]

jobs:
  backend:
    name: Backend Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install node_modules
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Lint
        run: npm run lint

  frontend:
    name: Frontend Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install node_modules
        run: npm install

      - name: Verify webpack config
        run: npx webpack configtest ./webpack.config.js

      - name: Build
        run: npm run build

      - name: Install node http-server
        run: npm install --global http-server

      - name: Serve files locally
        run: http-server ../build/production --port 8000 --proxy http://localhost:8000? > /dev/null 2>&1 &

      - name: Run Test
        run: npm run test

      - name: Run Lint
        run: npm run lint
